import { Accommodations, PropertyProps } from "@/interfaces";

import {
  BedDouble,
  Building,
  Trees,
  Home,
  // PalmTree,
  Sparkles,
  Waves,
  House,
  // Island,
  Tent,
  // Apartment,
  Factory,
  Castle,
  MountainSnow,
  TreePine,
  // Cabin,
  Landmark,
  Building2,
  Hotel,
  Mountain,
  Flower2,
  Bath,
  Gem,
  Crown,
  Scroll,
} from "lucide-react";
// import { Accommodations } from "@/interfaces/index.ts";

export const accommodations: Accommodations = [
  { label: "Rooms", Icon: BedDouble },
  { label: "Mansion", Icon: Landmark },
  { label: "Countryside", Icon: Trees },
  { label: "Villa", Icon: Home },
  // { label: "Tropical", Icon: PalmTree },
  { label: "New", Icon: Sparkles },
  { label: "Amazing pool", Icon: Waves },
  { label: "Beach house", Icon: House },
  // { label: "Island", Icon: Island },
  { label: "Camping", Icon: Tent },
  // { label: "Apartment", Icon: Apartment },
  { label: "House", Icon: Home },
  { label: "Lakefront", Icon: Waves },
  { label: "Farm house", Icon: Factory },
  { label: "Treehouse", Icon: TreePine },
  // { label: "Cabins", Icon: Cabin },
  { label: "Castles", Icon: Castle },
  { label: "Lakeside", Icon: Waves },
  { label: "Skiing", Icon: MountainSnow },
  { label: "Desert", Icon: Mountain },
  // { label: "Cottage", Icon: Cabin },
  { label: "Downtown", Icon: Building2 },
  { label: "Penthouse", Icon: Building },
  { label: "Ski lodge", Icon: MountainSnow },
  { label: "Boutique", Icon: Flower2 },
  { label: "Design", Icon: Bath },
  { label: "Historical", Icon: Scroll },
  { label: "Luxury", Icon: Crown },
  { label: "Private", Icon: Gem },
  { label: "Resort", Icon: Hotel },
];

// export const accommodations: Accommodations = [
//   { label: "Rooms", icon: "../public/assets/logos/living-room 1.svg" },
//   { label: "Mansion", icon: "../public/assets/logos/mansion 1.svg" },
//   { label: "Countryside", icon: "../public/assets/logos/farm 1.svg" },
//   { label: "Villa", icon: "../public/assets/logos/villa 1.svg" },
//   { label: "Tropical", icon: "../public/assets/logos/palm-tree 1.svg" },
//   { label: "New", icon: "../public/assets/logos/key-chain 1.svg" },
//   { label: "Amazing pool", icon: "../public/assets/logos/swimming-pool 1.svg" },
//   { label: "Beach house", icon: "../public/assets/logos/" },
//   { label: "Island", icon: GiIsland },
//   { label: "Camping", icon: GiCampingTent },
//   { label: "Apartment", icon: FaBuilding },
//   { label: "House", icon: FaHome },
//   { label: "Lakefront", icon: FaWater },
//   { label: "Farm house", icon: GiFarmTractor },
//   { label: "Treehouse", icon: GiTreehouse },
//   { label: "Cabins", icon: FaHome },
//   { label: "Castles", icon: GiCastle },
//   { label: "Lakeside", icon: FaWater },
//   { label: "Skiing", icon: FaSnowflake },
//   { label: "Desert", icon: GiDesert },
//   { label: "Cottage", icon: FaHome },
//   { label: "Downtown", icon: FaBuilding },
//   { label: "Penthouse", icon: FaHome },
//   { label: "Ski lodge", icon: FaSnowflake },
//   { label: "Boutique", icon: FaHotel },
//   { label: "Design", icon: FaHome },
//   { label: "Historical", icon: GiCastle },
//   { label: "Luxury", icon: FaHotel },
//   { label: "Private", icon: FaHome },
//   { label: "Resort", icon: FaHotel },
//   { label: "Spa", icon: FaSpa },
// ];

// export const accommodations: Accommodation = [
//   "Rooms",
//   "Mansion",
//   "Countryside",
//   "Villa",
//   "Tropical",
//   "New",
//   "Amazing pool",
//   "Beach house",
//   "Island",
//   "Camping",
//   "Apartment",
//   "House",
//   "Lakefront",
//   "Farm house",
//   "Treehouse",
//   "Cabins",
//   "Castles",
//   "Lakeside",
//   "Skiing",
//   "Desert",
//   "Cottage",
//   "Downtown",
//   "Penthouse",
//   "Ski lodge",
//   "Boutique",
//   "Design",
//   "Historical",
//   "Luxury",
//   "Private",
//   "Resort",
//   "Spa",
// ];

import HERO_IMAGE from "../public/assets/hero-section-image/Image1.png";

export const heroImage = HERO_IMAGE;

export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    name: "Villa Ocean Breeze",
    address: {
      state: "Seminyak",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: "https://example.com/image1.jpg",
    discount: "",
  },
  {
    name: "Mountain Escape Chalet",
    address: {
      state: "Aspen",
      city: "Colorado",
      country: "USA",
    },
    rating: 4.7,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://example.com/image2.jpg",
    discount: "30",
  },
  {
    name: "Cozy Desert Retreat",
    address: {
      state: "Palm Springs",
      city: "California",
      country: "USA",
    },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://example.com/image3.jpg",
    discount: "",
  },
  {
    name: "City Lights Penthouse",
    address: {
      state: "New York",
      city: "New York",
      country: "USA",
    },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://example.com/image4.jpg",
    discount: "15",
  },
  {
    name: "Riverside Cabin",
    address: {
      state: "Queenstown",
      city: "Otago",
      country: "New Zealand",
    },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: {
      bed: "3",
      shower: "2",
      occupants: "4-6",
    },
    image: "https://example.com/image5.jpg",
    discount: "20",
  },
  {
    name: "Modern Beachfront Villa",
    address: {
      state: "Sidemen",
      city: "Bali",
      country: "Indonesia",
    },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: {
      bed: "5",
      shower: "4",
      occupants: "8-10",
    },
    image: "https://example.com/image6.jpg",
    discount: "",
  },
  {
    name: "Lakeside Chalet",
    address: {
      state: "Banff",
      city: "Alberta",
      country: "Canada",
    },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image7.jpg",
    discount: "10",
  },
  {
    name: "Tropical Garden Villa",
    address: {
      state: "Koh Samui",
      city: "Surat Thani",
      country: "Thailand",
    },
    rating: 4.8,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "5-6",
    },
    image: "https://example.com/image8.jpg",
    discount: "25",
  },
  {
    name: "Urban Loft",
    address: {
      state: "Berlin",
      city: "Berlin",
      country: "Germany",
    },
    rating: 4.6,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-3",
    },
    image: "https://example.com/image9.jpg",
    discount: "",
  },
  {
    name: "Secluded Forest Cabin",
    address: {
      state: "Whistler",
      city: "British Columbia",
      country: "Canada",
    },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    offers: {
      bed: "4",
      shower: "2",
      occupants: "5-7",
    },
    image: "https://example.com/image10.jpg",
    discount: "40",
  },
  {
    name: "Cliffside Villa",
    address: {
      state: "Amalfi",
      city: "Salerno",
      country: "Italy",
    },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    price: 6000,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://example.com/image11.jpg",
    discount: "50",
  },
  {
    name: "Coastal Escape Villa",
    address: {
      state: "Noosa",
      city: "Queensland",
      country: "Australia",
    },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    price: 3400,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-6",
    },
    image: "https://example.com/image12.jpg",
    discount: "",
  },
  {
    name: "Historical Villa",
    address: {
      state: "Florence",
      city: "Tuscany",
      country: "Italy",
    },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    price: 2700,
    offers: {
      bed: "2",
      shower: "2",
      occupants: "2-4",
    },
    image: "https://example.com/image13.jpg",
    discount: "35",
  },
  {
    name: "Downtown Apartment",
    address: {
      state: "Tokyo",
      city: "Tokyo",
      country: "Japan",
    },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    price: 2200,
    offers: {
      bed: "1",
      shower: "1",
      occupants: "2",
    },
    image: "https://example.com/image14.jpg",
    discount: "",
  },
  {
    name: "Luxury Safari Lodge",
    address: {
      state: "Serengeti",
      city: "Mara",
      country: "Tanzania",
    },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    offers: {
      bed: "4",
      shower: "4",
      occupants: "6-8",
    },
    image: "https://example.com/image15.jpg",
    discount: "20",
  },
  {
    name: "Countryside Cottage",
    address: {
      state: "Cotswolds",
      city: "Gloucestershire",
      country: "UK",
    },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: {
      bed: "2",
      shower: "1",
      occupants: "2-4",
    },
    image: "https://example.com/image16.jpg",
    discount: "25",
  },
  {
    name: "Riverfront Mansion",
    address: {
      state: "Paris",
      city: "Île-de-France",
      country: "France",
    },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    price: 5000,
    offers: {
      bed: "4",
      shower: "3",
      occupants: "6-8",
    },
    image: "https://example.com/image17.jpg",
    discount: "30",
  },
  {
    name: "Ski Chalet",
    address: {
      state: "Zermatt",
      city: "Valais",
      country: "Switzerland",
    },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    price: 3900,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image18.jpg",
    discount: "",
  },
  {
    name: "Island Paradise Villa",
    address: {
      state: "Mahe",
      city: "Victoria",
      country: "Seychelles",
    },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    offers: {
      bed: "5",
      shower: "5",
      occupants: "8-10",
    },
    image: "https://example.com/image19.jpg",
    discount: "60",
  },
  {
    name: "Clifftop Retreat",
    address: {
      state: "Cape Town",
      city: "Western Cape",
      country: "South Africa",
    },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Checkin"],
    price: 4100,
    offers: {
      bed: "3",
      shower: "3",
      occupants: "4-5",
    },
    image: "https://example.com/image20.jpg",
    discount: "",
  },
];
